import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import { useState, useEffect } from "react";
import { LangContext } from "./CartContext";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Home from "./Home";
import About from "./About";
import Contact from "./Contact";
import ProductDetails from "./assets/ProductDetails";
import Cart from "./Cart";
import Checkout from "./Checkout";
import Category from "./Category";
import { CartProvider } from "./CartContext";

function App() {
  const [coin, setCoin] = useState(() => {
    return localStorage.getItem("coin") || "USD";
  });
  useEffect(() => {
    localStorage.setItem("coin", coin);
  }, [coin]);

  const [lang, setLang] = useState(() => {
    return localStorage.getItem("lang") || "en";
  });
  useEffect(() => {
    localStorage.setItem("lang", lang);
  }, [lang]);
  const trasnaltions = {
    en: {
      //  ======================= footer =======================
      ZENS: "ZENS",
      Lorem:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in nibh vehicula, facilisis magna ut, consectetur lorem. Proin eget tortor risus.",
      ConnectWithUs: "Connect With Us",
      Shop: "Shop",
      NewArrivals: "New Arrivals",
      Bestsellers: "Bestsellers",
      WomensClothing: "Women's Clothing",
      MensClothing: "Men's Clothing",
      Accessories: "Accessories",
      Sale: "Sale",
      Support: "Support",
      HelpCenter: "Help Center",
      OrderStatus: "Order Status",
      ShippingInfo: "Shipping Info",
      ReturnsExchanges: "Returns & Exchanges",
      SizeGuide: "Size Guide",
      ContactUs: "Contact Us",
      ContactInformation: "Contact Information",
      Map: "123 Fashion Street, New York, NY 10001",
      phone: "+1 (555) 123-4567",
      GMAIL: "hello@example.com",
      min: "Monday-Friday: 9am-6pmSaturday: 10am-4pmSunday: Closed",
      Copyright: "© Copyright NiceShop. All Rights Reserved.",
      DesignedBootstrapMade: "Designed by BootstrapMade",
      Terms: "Terms",
      Privacy: "Privacy",
      Cookies: "Cookies",
      //  ======================= Navbar =======================
      Needhelp: " Need help? Call us: +974 3994 1798",
      free1: "🚚 Free shipping on orders over $50",
      free2: "🚚 Free shipping on orders over $30",
      free3: "🎁 20% off on your first order",
      Home: "Home",
      About: "About",
      Category: "Category",
      ProductDetails: "Product Details",
      Cart: "Cart",
      Checkout: "Checkout",
      Featured: "Featured",
      NewArrivals: "NewArrivals",
      Sale: "Sale",
      Categories: "Categories",
      Searchproducts: "Search for products",
      Thecartisempty: "The cart is empty",
      Total: "Total",
      ViewCart: "View Cart",
      ViewCheckout: "View Checkout",
      Contact: "Contact",
      Megamenu: "Megamenu",
      navFeatured: "Featured",
      navNewArrivals: "New Arrivals",
      navSale: "Sale",
      navCategories: "Categories",
      // megamenu
      Clothing: "Clothing",
      MensWear: "Men's Wear",
      WomensWear: "Women's Wear",
      KidsCollection: "Kids Collection",
      Sportswear: "Sportswear",
      Accessories: "Accessories",
      Electronics: "Electronics",
      Smartphones: "Smartphones",
      Laptops: "Laptops",
      AudioDevices: "Audio Devices",
      SmartHome: "Smart Home",
      Accessories: "Accessories",
      HomeLiving: "Home & Living",
      Furniture: "Furniture",
      Decor: "Decor",
      Kitchen: "Kitchen",
      Bedding: "Bedding",
      Lighting: "Lighting",
      Beauty: "Beauty",
      Skincare: "Skincare",
      Makeup: "Makeup",
      Haircare: "Haircare",
      Fragrances: "Fragrances",
      PersonalCare: "Personal Care",
      Megamenu2: "Megamenu2",
      WOMEN: "WOMEN",
      MEN: "MEN",
      KIDS: "KIDS",
      ShirtsTops: "Shirts & Tops",
      CoatsOuterwear: "Coats & Outerwear",
      Underwear: "Underwear",
      Sweatshirts: "Sweatshirts",
      Dresses: "Dresses",
      Swimwear: "Swimwear",
      Viewall: "Viewall",
      Shoes: "Shoes",
      Boots: "Boots",
      Sandals: "Sandals",
      Heels: "Heels",
      Loafers: "Loafers",
      Slippers: "Slippers",
      Oxfords: "Oxfords",
      Handbags: "Handbags",
      Eyewear: "Eyewear",
      Hats: "Hats",
      Watches: "Watches",
      Jewelry: "Jewelry",
      Belts: "Belts",
      SpecialtySizes: "Specialty Sizes",
      PlusSize: "PlusSize",
      Petite: "Petite",
      WideShoes: "WideShoes",
      NarrowShoes: "NarrowShoes",
      //  ======================= Home =======================
      Discover: "Discover Amazing Products",
      Exploreourcurated:
        "Explore our curated collection of premium items designed to enhance your lifestyle. From fashion to tech, find everything you need with exclusive deals and fast shipping.",
      darkbtn: "Shop Now",
      whitebtn: "Browse Categories",
      trak: "Free Shipping",
      QualityGuarantee: "Quality Guarantee",
      Support: "24/7 Support",
      BestSeller: "Best Seller",
      SleekGamingPC:
        "Powerful modern gaming PC with sleek design and high performance",
      TrendingNow: "Trending Now",
      NewPCbuild: "New PC build",
      Discoverourlatestarrivals:
        "Ultimate gaming PC: Intel i9, RTX 5090, 64GB RAM, 2TB SSD, RGB lighting, lightning-fast performance.",
      ExploreCollection: "Explore Collection",
      Electronics: "Electronics",
      productsnum: " products",
      ShopNow: "Shop Now",
      Furniture: "Furniture",
      Clothing: "Clothing",
      Jewelry: "Jewelry",
      BestSellers: "Best Sellers",
      Necessitatibus:
        "Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit",
      // item1
      DesignerSeries: "Designer Series",
      Utenimadminimveniamquis: "Ut enim ad minim veniam quis",
      ADDTOCARD: "ADD TO CARD",
      PremiumCollection: "Designer Series",
      Maurisblanditaliquetelit: "Ut enim ad minim veniam quis",
      // item2
      Classic: "Classic Beige Sofa",
      Comfortable:
        "Comfortable fabric sofa with a classic design and a soft beige tone, perfect for everyday living rooms.",
      // item3
      SmartWatch: "Smart Watch",
      Modernsmartwatch:
        "Modern smart watch with fitness tracking and daily notifications.",
      // item4
      HPOmniBookLaptop: "HP OmniBook Laptop",
      Lightweight:
        "Lightweight laptop with smooth performance for work and everyday use.",
      // item5
      iPhone: "iPhone 14 Pro",
      Sleek: "Sleek modern smartphone with large screen and slim design.",
      // item6
      Wirelessearbuds: "Wireless earbuds",
      Wireless: "Wireless earbuds with clear sound and long battery life.",
      // item6
      EchoSpot: "Echo Spot",
      Smartalarmclock:
        "Smart alarm clock with Alexa+ assistant, ideal for nightstands.",
      // end
      TrendingNow: "Trending Now",
      BestSellers: "Best Sellers",
      FeaturedItems: "Featured Items",
      New: "New",
      PremiumLeatherTote: "Premium Leather Tote",
      StatementEarrings: "Statement Earrings",
      OrganicCottonShirt: "Organic Cotton Shirt",
      Limited: "Limited Time ",
      off: "50% OFF",
      ExclusiveFlashSale: "Exclusive Flash Sale",
      Don: "Don't miss out on our biggest sale of the year. Premium quality products at unbeatable prices for the next 48 hours only.",
      Days: "Days",
      Hours: "Hours",
      Minutes: "Minutes",
      Seconds: "Seconds",
      //  ======================= About =======================
      AboutUs: "About Us",
      Nemo: "Nemo enim ipsam voluptatem quia voluptas aspernatur",
      Temporibusautem:
        "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
      Itaque:
        "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
      Ameteosut:
        "Amet eos ut. Officiis soluta ab id dolor non sint. Corporis omnis consequatur quisquam ex consequuntur quo omnis. Quo eligendi cum. Amet mollitia qui quidem dolores praesentium quasi ut et.",
      Atveroeos: "At vero eos",
      Nam: "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat.",
      Sedutperspiciatis: "Sed ut perspiciatis",
      At: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.",
      Nemoenimipsam: "Nemo enim ipsam",
      Nequeporroquisquam:
        "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam.",
      HappyClients: "Happy Clients",
      consequunturquae: "consequuntur quae",
      Projects: "Projects ",
      adipisciatquecumquiaaut: "adipisci atque cum quia aut",
      HoursOfSupport: "Hours Of Support",
      autcommodiquaerat: "aut commodi quaerat",
      HardWorkers: "Hard Workers",
      rerumdolor: "rerum asperiores dolor",
      Implementing:
        "Exceptional service delivery and innovative solutions have transformed our business operations, leading to remarkable growth and enhanced customer satisfaction across all touchpoints.",
      DanielMorgan: "Daniel Morgan",
      ChiefInnovationOfficer: "Chief Innovation Officer",
      Innovativeapproachto:
        "Innovative approach to user experience design has significantly enhanced our platform's engagement metrics and customer retention rates.",
      NathanBrooks: "Nathan Brooks",
      UXDirector: "UX Director",
      Professionalexpertiseanddedicationhave:
        "Professional expertise and dedication have significantly improved our project delivery timelines and quality metrics.",
      ChristopherLee: "Christopher Lee",
      TechnicalDirector: "Technical Director",
      //  ======================= Contact =======================
      OurAddress: "Our Address",
      Maple: "1842 Maple Avenue, Portland, Oregon 97204",
      EmailAddress: "Email Address",
      email: "alisahari2008@gmail.com",
      HoursOperation: "Hours of Operation",
      Sunday1: "Sunday-Fri: 9 AM - 6 PM",
      Saturday1: "Saturday: 9 AM - 4 PM",
      GetinTouch: "Get in Touch",
      // * form
      FirstName: "First Name",
      EmailAddress: "Email Address",
      Subject: "Subject",
      WriteMessage: "Write Message...",
      SENDMESSAGE: "SEND MESSAGE",
      //  ========================= Cart =========================
      // !warning
      warning1: "“Justo Finibus” removed.",
      warning2: "Your cart is currently empty.",
      warning3: "Your cart is currently empty.",
      warningbtn1: "Undo?",
      warningbtn2: "Return to shop",
      cardProduct: "Product",
      cardQuantity: "Quantity",
      cardSubtotal: "Subtotal",
      Carttotals: "Cart totals",
      Subtotal: "Subtotal",
      Total: "Total",
      // !
      SuggestedProducts: "Suggested Products",
      Congratulations: "Congratulations! You got free shipping 🎉",
      Add: "Add",
      shipping: "more to get free shipping!",
      Proceedtocheckout: "Proceed to checkout",
      Applycoupon: "Apply coupon",
      Couponcode: "Coupon code",
      discount: "30% discount",
      discount2: "8% discount applied",
      discount3: "18% discount applied",
      discount4: "22% discount applied",
      discount5: "35% discount applied",
      Giveacoupon: "Give me a coupon",
      Loding: "Loding...",
      Clearcart: "Clear cart",
      Remove: "Remove",
      Color: "Color",
      Size: "Size",
      Price: "Price",
      Quantity: "Quantity",
      Total: "Total",
      OrderSummary: "Order Summary",
      Shipping: "Shipping",
      StandardDelivery: "Standard Delivery -",
      ExpressDelivery: "Express Delivery ",
      Free: "Free Shipping (Orders over $300)",
      Tax: "Tax",
      Discount: "Discount",
      ProceedtoCheckout: "Proceed to Checkout ",
      ContinueShopping: "Continue Shopping",
      WeAccept: "We Accept",
      //  ========================= Checkout =========================
      SecureCheckout: "Secure Checkout",
      Items: "Items",
      CustomerInformation: "Customer Information",
      // ? form 1
      FirstName: "First Name",
      yourFirstName: "Your First Name",
      LastName: "Last Name",
      yourLastName: "Your Last Name",
      EmailAddress: "Email Address",
      yourEmail: "Your Email",
      PhoneNumber: "Phone Number",
      yourPhoneNumber: "Your Phone Number",
      //? form 2
      ShippingAddress: "Shipping Address",
      StreetAddress: "Street Address",
      Apartment: "Apartment, Suite, etc. (optional)",
      Apartment2: "Apartment, Suite,Unit,etc.",
      City: "City",
      State: "State",
      ZIPCode: "ZIP Code",
      Country: "Country",
      option1: "Select Country",
      option2: "United States",
      option3: "Canada",
      option4: "United Kingdom",
      option5: "Australia",
      option6: "Germany",
      option7: "France",
      Savethis: "Save this address for future orders",
      Billing: "Billing address same as shipping",
      // ? form 3

      PaymentMethod: "Payment Method",
      CreditDebitCard: "Credit / Debit Card",
      PayPal: "PayPal",
      ApplePay: "Apple Pay",
      CardNumber: "Card Number",
      ExpirationDate: "Expiration Date",
      Security: "Security Code (CVV)",
      NameonCard: "Name on Card",
      JohnDoe: "John Doe",
      Youwill:
        "You will be redirected to PayPal to complete your purchase securely.",
      Youwill2: "You will be prompted to authorize payment with Apple Pay.",
      // ? form 4
      Review: "Review & Place Order",
      Iagreetothe: "I agree to the",
      TermsandConditions: " Terms and Conditions",
      and: "and",
      PrivacyPolicy: " Privacy Policy",
      IUnderstand: "I Understand",
      PlaceOrder: "Place Order",
      //  ========================= Category =========================
      Categories: "Categories",
      PriceRange: "Price Range",
      ApplyFilter: "Apply Filter",
      FilterbyBrand: "Filter by Brand",
      FilterbyColor: "Filter by Color",
      ClearAll: "Clear All",
      SearchProducts: "Search Products",
      PriceRange: "PriceRange",
      SortBy: "SortBy",
      View: "View",
      Electronics: "Electronics",
      MobilePhonesandAccessories: "Mobile Phones and Accessories",
      ComputersandLaptops: "Computers and Laptops",
      HeadphonesandAudioDevices: "Headphones and Audio Devices",
      SmartDevices: "Smart Devices",
      Furniture: "Furniture",
      Bedrooms: "Bedrooms",
      Sofasandseating: "Sofas and seating",
      Kitchensandhouseholdappliances: "Kitchens and household appliances",
      Decorandlighting: "Decor and lighting",
      Clothing: "Clothing",
      MensClothing: "Men's Clothing",
      ChildrensClothing: "Children's Clothing",
      Shoes: "Shoes",
      ClothingAccessories: "Clothing Accessories",
      Jewelry: "Jewelry",
      MensRings: "Men's Rings",
      BraceletsandNecklaces: "Bracelets and Necklaces",
      Watches: "Watches",
      MetalAccessories: "Metal Accessories",
      PriceRange: "Price Range",
    },

    ar: {
      ZENS: "ZENS",
      Lorem:
        "لوريم إيبسوم هو نص تجريبي يُستخدم في تصميم المحتوى. يهدف إلى ملء المساحات دون تشتيت الانتباه بالمحتوى الفعلي.",
      ConnectWithUs: "تواصل معنا",
      Shop: "المتجر",
      NewArrivals: "وصل حديثًا",
      Bestsellers: "الأكثر مبيعًا",
      WomensClothing: "ملابس نسائية",
      MensClothing: "ملابس رجالية",
      Accessories: "إكسسوارات",
      Sale: "تخفيضات",
      Support: "الدعم",
      HelpCenter: "مركز المساعدة",
      OrderStatus: "حالة الطلب",
      ShippingInfo: "معلومات الشحن",
      ReturnsExchanges: "الإرجاع والاستبدال",
      SizeGuide: "دليل المقاسات",
      ContactUs: "اتصل بنا",
      ContactInformation: "معلومات الاتصال",
      Map: "123 شارع فاشن، نيويورك، NY 10001",
      phone: "+1 (555) 123-4567",
      GMAIL: "hello@example.com",
      min: "من الإثنين إلى الجمعة: 9 صباحًا - 6 مساءً | السبت: 10 صباحًا - 4 مساءً | الأحد: مغلق",
      Copyright: "© حقوق النشر NiceShop. جميع الحقوق محفوظة.",
      DesignedBootstrapMade: "تم التصميم بواسطة BootstrapMade",
      Terms: "الشروط",
      Privacy: "الخصوصية",
      Cookies: "ملفات تعريف الارتباط",
      // home ======================================
      Discover: "اكتشف منتجات مذهلة",
      Exploreourcurated:
        "استكشف مجموعتنا المختارة من المنتجات الفاخرة المصممة لتعزيز أسلوب حياتك. من الأزياء إلى التكنولوجيا، اعثر على كل ما تحتاجه مع عروض حصرية وشحن سريع.",
      darkbtn: "تسوق الآن",
      whitebtn: "تصفح الفئات",
      trak: "شحن مجاني",
      QualityGuarantee: "ضمان الجودة",
      Support: "دعم 24/7",
      BestSeller: "الأكثر مبيعًا",
      SleekGamingPC: "كمبيوتر ألعاب حديث وقوي بتصميم أنيق وأداء عالي",
      TrendingNow: "الرائج الآن",
      NewPCbuild: "تجميعة كمبيوتر جديدة",
      Discoverourlatestarrivals:
        "كمبيوتر ألعاب فائق: Intel i9، RTX 5090، ذاكرة 64 جيجابايت، قرص SSD بسعة 2 تيرابايت، إضاءة RGB، وأداء فائق السرعة.",
      ExploreCollection: "استكشف المجموعة",
      Electronics: "إلكترونيات",
      productsnum: " منتجات",
      ShopNow: "تسوق الآن",
      Furniture: "أثاث",
      Clothing: "ملابس",
      Jewelry: "مجوهرات",
      BestSellers: "الأكثر مبيعًا",
      Necessitatibus: "نوفر لك أفضل المنتجات بجودة عالية وتصميم مميز",
      DesignerSeries: "السلسلة المصممة",
      Utenimadminimveniamquis: "تصميم أنيق يلبي احتياجاتك اليومية",
      ADDTOCARD: "أضف إلى السلة",
      PremiumCollection: "السلسلة المصممة",
      Maurisblanditaliquetelit: "جودة عالية بتصميم عصري",
      Classic: "أريكة بيج كلاسيكية",
      Comfortable:
        "أريكة قماش مريحة بتصميم كلاسيكي ولون بيج ناعم، مثالية لغرف المعيشة اليومية.",
      SmartWatch: "ساعة ذكية",
      Modernsmartwatch:
        "ساعة ذكية عصرية مع تتبع اللياقة البدنية والإشعارات اليومية.",
      HPOmniBookLaptop: "لابتوب HP OmniBook",
      Lightweight: "لابتوب خفيف الوزن بأداء سلس للعمل والاستخدام اليومي.",
      FeaturedItems: "منتجات مميزة",
      New: "جديد",
      PremiumLeatherTote: "حقيبة جلد فاخرة",
      StatementEarrings: "أقراط مميزة",
      OrganicCottonShirt: "قميص قطن عضوي",
      Limited: "لفترة محدودة",
      off: "خصم 50%",
      ExclusiveFlashSale: "عرض خاطف حصري",
      Don: "لا تفوت أكبر عروضنا لهذا العام. منتجات بجودة عالية بأسعار لا تقاوم لمدة 48 ساعة فقط.",
      Days: "أيام",
      Hours: "ساعات",
      Minutes: "دقائق",
      Seconds: "ثواني",
      AboutUs: "من نحن",
      Nemo: "لا يوجد أحد يحب الألم لذاته أو يسعى إليه",
      Temporibusautem:
        "في بعض الأوقات والظروف تفرض الواجبات أو الضرورات أمورًا تجعلنا نتحمل ما قد نرفضه في غيرها.",
      Itaque:
        "ولهذا فإن اختيار المتعة أو رفض الألم يكون أحيانًا بدافع الحكمة والعقل.",
      Ameteosut:
        "أحب هذه الأمور. الواجبات تؤدى أحيانًا دون ألم. فجميع الأعمال تخضع لنتائجها. والاختيار يتم بعناية.",
      Atveroeos: "ولكن في الحقيقة",
      Nam: "في الوقت الذي نكون فيه أحرارًا في الاختيار، لا شيء يمنعنا من اختيار الأفضل.",
      Sedutperspiciatis: "لكن من منظور آخر",
      At: "نحن نلوم أولئك الذين يستسلمون للملذات دون تفكير.",
      Nemoenimipsam: "لا أحد يحب",
      Nequeporroquisquam: "ولا يوجد شخص يرغب في الألم لأنه ألم بحد ذاته.",
      HappyClients: "عملاء سعداء",
      consequunturquae: "نتائج مميزة",
      Projects: "المشاريع",
      adipisciatquecumquiaaut: "نمو وتطور مستمر",
      HoursOfSupport: "ساعات الدعم",
      autcommodiquaerat: "خدمة متميزة",
      HardWorkers: "فريق عمل مجتهد",
      rerumdolor: "خبرات قوية",
      Implementing:
        "تقديم خدمات استثنائية وحلول مبتكرة ساهم في تطوير أعمالنا وتحقيق رضا العملاء.",
      DanielMorgan: "دانيال مورغان",
      ChiefInnovationOfficer: "رئيس الابتكار",
      Innovativeapproachto:
        "النهج المبتكر في تجربة المستخدم عزز من تفاعل العملاء وولائهم.",
      NathanBrooks: "ناثان بروكس",
      UXDirector: "مدير تجربة المستخدم",
      Professionalexpertiseanddedicationhave:
        "الخبرة المهنية والتفاني حسّنا جودة المشاريع وسرعة تنفيذها.",
      ChristopherLee: "كريستوفر لي",
      TechnicalDirector: "المدير التقني",
      OurAddress: "عنواننا",
      Maple: "1842 شارع مابل، بورتلاند، أوريغون 97204",
      EmailAddress: "عنوان البريد الإلكتروني",
      email: "alisahari2008@gmail.com",
      HoursOperation: "ساعات العمل",
      Sunday1: "الأحد - الجمعة: 9 صباحًا - 6 مساءً",
      Saturday1: "السبت: 9 صباحًا - 4 مساءً",
      GetinTouch: "تواصل معنا",

      // * form
      FirstName: "الاسم الأول",
      EmailAddress: "عنوان البريد الإلكتروني",
      Subject: "الموضوع",
      WriteMessage: "اكتب رسالتك...",
      SENDMESSAGE: "إرسال الرسالة",

      // ========================= Cart =========================
      warning1: "تمت إزالة “Justo Finibus”.",
      warning2: "سلة التسوق فارغة حالياً.",
      warning3: "سلة التسوق فارغة حالياً.",
      warningbtn1: "تراجع؟",
      warningbtn2: "العودة إلى المتجر",
      cardProduct: "المنتج",
      cardQuantity: "الكمية",
      cardSubtotal: "المجموع الفرعي",
      Carttotals: "إجمالي السلة",
      Subtotal: "المجموع الفرعي",
      Total: "الإجمالي",
      SuggestedProducts: "منتجات مقترحة",
      Congratulations: "تهانينا! حصلت على شحن مجاني 🎉",
      Add: "إضافة",
      shipping: "متبقي للحصول على شحن مجاني!",
      Proceedtocheckout: "المتابعة للدفع",
      Applycoupon: "تطبيق الكوبون",
      Couponcode: "رمز الكوبون",
      discount: "خصم 30%",
      discount2: "تم تطبيق خصم 8%",
      discount3: "تم تطبيق خصم 18%",
      discount4: "تم تطبيق خصم 22%",
      discount5: "تم تطبيق خصم 35%",
      Giveacoupon: "أعطني كوبون",
      Loding: "جاري التحميل...",
      Clearcart: "تفريغ السلة",
      Remove: "إزالة",
      Color: "اللون",
      Size: "المقاس",
      Price: "السعر",
      Quantity: "الكمية",
      Total: "الإجمالي",
      OrderSummary: "ملخص الطلب",
      Shipping: "الشحن",
      StandardDelivery: "توصيل عادي -",
      ExpressDelivery: "توصيل سريع",
      Free: "شحن مجاني (للطلبات فوق 300$)",
      Tax: "الضريبة",
      Discount: "الخصم",
      ProceedtoCheckout: "المتابعة للدفع",
      ContinueShopping: "متابعة التسوق",
      WeAccept: "نقبل",
      SecureCheckout: "إتمام الشراء الآمن",
      Items: "المنتجات",
      CustomerInformation: "معلومات العميل",

      // form 1
      FirstName: "الاسم الأول",
      yourFirstName: "اسمك الأول",
      LastName: "اسم العائلة",
      yourLastName: "اسم العائلة",
      EmailAddress: "البريد الإلكتروني",
      yourEmail: "بريدك الإلكتروني",
      PhoneNumber: "رقم الهاتف",
      yourPhoneNumber: "رقم هاتفك",

      // form 2
      ShippingAddress: "عنوان الشحن",
      StreetAddress: "عنوان الشارع",
      Apartment: "شقة، جناح، إلخ (اختياري)",
      Apartment2: "شقة، جناح، وحدة، إلخ",
      City: "المدينة",
      State: "الولاية / المنطقة",
      ZIPCode: "الرمز البريدي",
      Country: "الدولة",
      option1: "اختر الدولة",
      option2: "الولايات المتحدة",
      option3: "كندا",
      option4: "المملكة المتحدة",
      option5: "أستراليا",
      option6: "ألمانيا",
      option7: "فرنسا",
      Savethis: "حفظ هذا العنوان للطلبات المستقبلية",
      Billing: "عنوان الفواتير نفس عنوان الشحن",

      // form 3
      PaymentMethod: "طريقة الدفع",
      CreditDebitCard: "بطاقة ائتمان / خصم",
      PayPal: "باي بال",
      ApplePay: "آبل باي",
      CardNumber: "رقم البطاقة",
      ExpirationDate: "تاريخ الانتهاء",
      Security: "رمز الأمان (CVV)",
      NameonCard: "الاسم على البطاقة",
      JohnDoe: "جون دو",
      Youwill: "سيتم تحويلك إلى باي بال لإتمام عملية الشراء بشكل آمن.",
      Youwill2: "سيُطلب منك تأكيد الدفع باستخدام آبل باي.",

      // form 4
      Review: "مراجعة وتأكيد الطلب",
      Iagreetothe: "أوافق على",
      TermsandConditions: " الشروط والأحكام",
      and: "و",
      PrivacyPolicy: " سياسة الخصوصية",
      IUnderstand: "أفهم ذلك",
      PlaceOrder: "إتمام الطلب",
      Categories: "التصنيفات",
      PriceRange: "نطاق السعر",
      ApplyFilter: "تطبيق الفلتر",
      FilterbyBrand: "التصفية حسب العلامة التجارية",
      FilterbyColor: "التصفية حسب اللون",
      ClearAll: "مسح الكل",
      SearchProducts: "بحث عن المنتجات",
      SortBy: "ترتيب حسب",
      View: "العرض",
      Electronics: "الإلكترونيات",
      MobilePhonesandAccessories: "الهواتف المحمولة وملحقاتها",
      ComputersandLaptops: "أجهزة الكمبيوتر واللابتوبات",
      HeadphonesandAudioDevices: "سماعات الرأس وأجهزة الصوت",
      SmartDevices: "الأجهزة الذكية",
      Furniture: "الأثاث",
      Bedrooms: "غرف النوم",
      Sofasandseating: "الأرائك ومناطق الجلوس",
      Kitchensandhouseholdappliances: "المطابخ والأجهزة المنزلية",
      Decorandlighting: "الديكور والإضاءة",
      Clothing: "الملابس",
      MensClothing: "ملابس رجالية",
      ChildrensClothing: "ملابس الأطفال",
      Shoes: "الأحذية",
      ClothingAccessories: "إكسسوارات الملابس",
      Jewelry: "المجوهرات",
      MensRings: "خواتم رجالية",
      BraceletsandNecklaces: "الأساور والقلائد",
      Watches: "الساعات",
      MetalAccessories: "إكسسوارات معدنية",
      Needhelp: "هل تحتاج مساعدة؟ اتصل بنا: +974 3994 1798",
      free1: "🚚 شحن مجاني للطلبات التي تزيد عن $50",
      free2: "🚚 شحن مجاني للطلبات التي تزيد عن $30",
      free3: "🎁 خصم 20% على طلبك الأول",
      Home: "الرئيسية",
      About: "من نحن",
      Category: "الفئات",
      ProductDetails: "تفاصيل المنتج",
      Cart: "سلة التسوق",
      Checkout: "إتمام الشراء",
      Featured: "مميز",
      NewArrivals: "وصل حديثاً",
      Sale: "تخفيضات",
      Categories: "التصنيفات",
      Searchproducts: "ابحث عن المنتجات",
      Thecartisempty: "سلة التسوق فارغة",
      Total: "الإجمالي",
      ViewCart: "عرض السلة",
      ViewCheckout: "عرض الشراء",
      Contact: "اتصل بنا",
      // megamenu - Arabic
      Clothing: "الملابس",
      MensWear: "ملابس رجالية",
      WomensWear: "ملابس نسائية",
      KidsCollection: "مجموعة الأطفال",
      Sportswear: "ملابس رياضية",
      Accessories: "إكسسوارات",
      Electronics: "إلكترونيات",
      Smartphones: "هواتف ذكية",
      Laptops: "أجهزة لابتوب",
      AudioDevices: "أجهزة صوتية",
      SmartHome: "منزل ذكي",
      HomeLiving: "المنزل والمعيشة",
      Furniture: "أثاث",
      Decor: "ديكور",
      Kitchen: "مطبخ",
      Bedding: "مفارش وأسرة",
      Lighting: "إضاءة",
      Beauty: "جمال",
      Skincare: "العناية بالبشرة",
      Makeup: "مكياج",
      Haircare: "العناية بالشعر",
      Fragrances: "عطور",
      PersonalCare: "العناية الشخصية",
      Megamenu2: "قائمة ضخمة 2",
      Megamenu: "قائمة ضخمة 2",
      WOMEN: "نساء",
      MEN: "رجال",
      KIDS: "أطفال",
      ShirtsTops: "قمصان وبلوزات",
      CoatsOuterwear: "معاطف وملابس خارجية",
      Underwear: "ملابس داخلية",
      Sweatshirts: "سويت شيرت",
      Dresses: "فساتين",
      Swimwear: "ملابس سباحة",
      Viewall: "عرض الكل",
      Shoes: "أحذية",
      Boots: "بسطار / بوت",
      Sandals: "صنادل",
      Heels: "أحذية كعب",
      Loafers: "أحذية لوفر",
      Slippers: "شباشب",
      Oxfords: "أحذية أكسفورد",
      Handbags: "حقائب يد",
      Eyewear: "نظارات",
      Hats: "قبعات",
      Watches: "ساعات",
      Jewelry: "مجوهرات",
      Belts: "أحزمة",
      SpecialtySizes: "مقاسات خاصة",
      PlusSize: "مقاسات كبيرة",
      Petite: "مقاسات صغيرة (Petite)",
      WideShoes: "أحذية عريضة",
      NarrowShoes: "أحذية ضيقة",
    },
    tr: {
      ZENS: "ZENS",
      Lorem:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in nibh vehicula, facilisis magna ut, consectetur lorem. Proin eget tortor risus.",
      ConnectWithUs: "Bizimle Bağlantı Kurun",
      Shop: "Mağaza",
      NewArrivals: "Yeni Gelenler",
      Bestsellers: "Çok Satanlar",
      WomensClothing: "Kadın Giyim",
      MensClothing: "Erkek Giyim",
      Accessories: "Aksesuarlar",
      Sale: "İndirim",
      Support: "Destek",
      HelpCenter: "Yardım Merkezi",
      OrderStatus: "Sipariş Durumu",
      ShippingInfo: "Kargo Bilgileri",
      ReturnsExchanges: "İade & Değişim",
      SizeGuide: "Beden Rehberi",
      ContactUs: "Bizimle İletişime Geçin",
      ContactInformation: "İletişim Bilgileri",
      Map: "123 Fashion Street, New York, NY 10001",
      phone: "+1 (555) 123-4567",
      GMAIL: "hello@example.com",
      min: "Pazartesi-Cuma: 09:00-18:00 Cumartesi: 10:00-16:00 Pazar: Kapalı",
      Copyright: "© Telif Hakkı NiceShop. Tüm Hakları Saklıdır.",
      DesignedBootstrapMade: "BootstrapMade tarafından tasarlanmıştır",
      Terms: "Şartlar",
      Privacy: "Gizlilik",
      Cookies: "Çerezler",
      // home ====================================================
      Discover: "Harika Ürünleri Keşfet",
      Exploreourcurated:
        "Yaşam tarzınızı geliştirmek için tasarlanmış premium ürünlerden oluşan özel koleksiyonumuzu keşfedin. Modadan teknolojiye, ihtiyacınız olan her şeyi özel fırsatlar ve hızlı kargo ile bulun.",
      darkbtn: "Şimdi Alışveriş Yap",
      whitebtn: "Kategorilere Göz At",
      trak: "Ücretsiz Kargo",
      QualityGuarantee: "Kalite Garantisi",
      Support: "7/24 Destek",
      BestSeller: "Çok Satan",
      SleekGamingPC:
        "Şık tasarıma ve yüksek performansa sahip güçlü modern oyun bilgisayarı",
      TrendingNow: "Şu Anda Trend",
      NewPCbuild: "Yeni PC Toplama",
      Discoverourlatestarrivals:
        "Üst düzey oyun bilgisayarı: Intel i9, RTX 5090, 64GB RAM, 2TB SSD, RGB aydınlatma ve ultra hızlı performans.",
      ExploreCollection: "Koleksiyonu Keşfet",
      Electronics: "Elektronik",
      productsnum: " ürün",
      ShopNow: "Şimdi Satın Al",
      Furniture: "Mobilya",
      Clothing: "Giyim",
      Jewelry: "Takı",
      BestSellers: "En Çok Satanlar",
      Necessitatibus: "İhtiyaçlarınıza uygun yüksek kaliteli ve şık ürünler",
      DesignerSeries: "Tasarımcı Serisi",
      Utenimadminimveniamquis: "Günlük kullanım için şık tasarım",
      ADDTOCARD: "SEPETE EKLE",
      PremiumCollection: "Tasarımcı Serisi",
      Maurisblanditaliquetelit: "Modern tasarım ve üstün kalite",
      Classic: "Klasik Bej Kanepe",
      Comfortable:
        "Klasik tasarıma ve yumuşak bej renge sahip, günlük oturma odaları için ideal rahat kumaş kanepe.",
      SmartWatch: "Akıllı Saat",
      Modernsmartwatch:
        "Fitness takibi ve günlük bildirimlere sahip modern akıllı saat.",
      HPOmniBookLaptop: "HP OmniBook Dizüstü Bilgisayar",
      Lightweight:
        "İş ve günlük kullanım için hafif ve akıcı performans sunan dizüstü bilgisayar.",
      FeaturedItems: "Öne Çıkan Ürünler",
      New: "Yeni",
      PremiumLeatherTote: "Premium Deri Çanta",
      StatementEarrings: "Gösterişli Küpeler",
      OrganicCottonShirt: "Organik Pamuklu Gömlek",
      Limited: "Sınırlı Süre",
      off: "%50 İndirim",
      ExclusiveFlashSale: "Özel Flaş İndirim",
      Don: "Yılın en büyük indirimini kaçırmayın. Premium ürünler, sadece 48 saat boyunca kaçırılmayacak fiyatlarla.",
      Days: "Gün",
      Hours: "Saat",
      Minutes: "Dakika",
      Seconds: "Saniye",
      AboutUs: "Hakkımızda",
      Nemo: "Kimse acıyı sırf acı olduğu için sevmez",
      Temporibusautem:
        "Bazı zamanlarda ve koşullarda, görevler veya zorunluluklar bizi hoşlanmadığımız şeyleri kabullenmeye zorlar.",
      Itaque: "Bu yüzden bazen zevkleri seçer, bazen de acılardan kaçınırız.",
      Ameteosut:
        "Bu şeyleri severiz. Görevler bazen acısız yerine getirilir. Her şey sonuçlarına bağlıdır.",
      Atveroeos: "Ama gerçekte",
      Nam: "Seçim özgürlüğüne sahip olduğumuzda, en iyiyi seçmemizi engelleyen hiçbir şey yoktur.",
      Sedutperspiciatis: "Ancak farklı bir bakış açısından",
      At: "Düşünmeden zevklere kapılanları eleştiririz.",
      Nemoenimipsam: "Kimse sevmez",
      Nequeporroquisquam: "Ve hiç kimse acıyı, sadece acı olduğu için istemez.",
      HappyClients: "Mutlu Müşteriler",
      consequunturquae: "Etkili sonuçlar",
      Projects: "Projeler",
      adipisciatquecumquiaaut: "Sürekli gelişim",
      HoursOfSupport: "Destek Saatleri",
      autcommodiquaerat: "Kaliteli hizmet",
      HardWorkers: "Çalışkan Ekip",
      rerumdolor: "Güçlü deneyim",
      Implementing:
        "Üstün hizmet sunumu ve yenilikçi çözümler, iş süreçlerimizi geliştirerek müşteri memnuniyetini artırdı.",
      DanielMorgan: "Daniel Morgan",
      ChiefInnovationOfficer: "Baş İnovasyon Sorumlusu",
      Innovativeapproachto:
        "Kullanıcı deneyimine yenilikçi yaklaşım, platform etkileşimini artırdı.",
      NathanBrooks: "Nathan Brooks",
      UXDirector: "UX Direktörü",
      Professionalexpertiseanddedicationhave:
        "Profesyonel uzmanlık ve özveri, proje kalitesini ve teslim süresini iyileştirdi.",
      ChristopherLee: "Christopher Lee",
      TechnicalDirector: "Teknik Direktör",
      OurAddress: "Adresimiz",
      Maple: "1842 Maple Caddesi, Portland, Oregon 97204",
      EmailAddress: "E-posta Adresi",
      email: "alisahari2008@gmail.com",
      HoursOperation: "Çalışma Saatleri",
      Sunday1: "Pazar - Cuma: 09:00 - 18:00",
      Saturday1: "Cumartesi: 09:00 - 16:00",
      GetinTouch: "Bizimle İletişime Geçin",

      // * form
      FirstName: "Ad",
      EmailAddress: "E-posta Adresi",
      Subject: "Konu",
      WriteMessage: "Mesajınızı yazın...",
      SENDMESSAGE: "MESAJ GÖNDER",

      // ========================= Cart =========================
      warning1: "“Justo Finibus” kaldırıldı.",
      warning2: "Sepetiniz şu anda boş.",
      warning3: "Sepetiniz şu anda boş.",
      warningbtn1: "Geri al?",
      warningbtn2: "Mağazaya dön",
      cardProduct: "Ürün",
      cardQuantity: "Adet",
      cardSubtotal: "Ara Toplam",
      Carttotals: "Sepet Toplamları",
      Subtotal: "Ara Toplam",
      Total: "Toplam",
      SuggestedProducts: "Önerilen Ürünler",
      Congratulations: "Tebrikler! Ücretsiz kargo kazandınız 🎉",
      Add: "Ekle",
      shipping: "ücretsiz kargo için kaldı!",
      Proceedtocheckout: "Ödemeye geç",
      Applycoupon: "Kuponu uygula",
      Couponcode: "Kupon kodu",
      discount: "%30 indirim",
      discount2: "%8 indirim uygulandı",
      discount3: "%18 indirim uygulandı",
      discount4: "%22 indirim uygulandı",
      discount5: "%35 indirim uygulandı",
      Giveacoupon: "Bana kupon ver",
      Loding: "Yükleniyor...",
      Clearcart: "Sepeti temizle",
      Remove: "Kaldır",
      Color: "Renk",
      Size: "Beden",
      Price: "Fiyat",
      Quantity: "Adet",
      Total: "Toplam",
      OrderSummary: "Sipariş Özeti",
      Shipping: "Kargo",
      StandardDelivery: "Standart Teslimat -",
      ExpressDelivery: "Ekspres Teslimat",
      Free: "Ücretsiz Kargo (300$ üzeri siparişler)",
      Tax: "Vergi",
      Discount: "İndirim",
      ProceedtoCheckout: "Ödemeye Geç",
      ContinueShopping: "Alışverişe Devam Et",
      WeAccept: "Kabul Ediyoruz",
      SecureCheckout: "Güvenli Ödeme",
      Items: "Ürünler",
      CustomerInformation: "Müşteri Bilgileri",

      // form 1
      FirstName: "Ad",
      yourFirstName: "Adınız",
      LastName: "Soyad",
      yourLastName: "Soyadınız",
      EmailAddress: "E-posta Adresi",
      yourEmail: "E-posta Adresiniz",
      PhoneNumber: "Telefon Numarası",
      yourPhoneNumber: "Telefon Numaranız",

      // form 2
      ShippingAddress: "Teslimat Adresi",
      StreetAddress: "Sokak Adresi",
      Apartment: "Apartman, Daire vb. (isteğe bağlı)",
      Apartment2: "Apartman, Daire, Birim vb.",
      City: "Şehir",
      State: "Eyalet / Bölge",
      ZIPCode: "Posta Kodu",
      Country: "Ülke",
      option1: "Ülke Seçin",
      option2: "Amerika Birleşik Devletleri",
      option3: "Kanada",
      option4: "Birleşik Krallık",
      option5: "Avustralya",
      option6: "Almanya",
      option7: "Fransa",
      Savethis: "Bu adresi gelecekteki siparişler için kaydet",
      Billing: "Fatura adresi teslimat adresi ile aynı",

      // form 3
      PaymentMethod: "Ödeme Yöntemi",
      CreditDebitCard: "Kredi / Banka Kartı",
      PayPal: "PayPal",
      ApplePay: "Apple Pay",
      CardNumber: "Kart Numarası",
      ExpirationDate: "Son Kullanma Tarihi",
      Security: "Güvenlik Kodu (CVV)",
      NameonCard: "Kart Üzerindeki İsim",
      JohnDoe: "John Doe",
      Youwill:
        "Satın alma işlemini güvenli bir şekilde tamamlamak için PayPal'a yönlendirileceksiniz.",
      Youwill2: "Apple Pay ile ödemeyi onaylamanız istenecek.",

      // form 4
      Review: "Siparişi İncele ve Onayla",
      Iagreetothe: "Kabul ediyorum",
      TermsandConditions: " Şartlar ve Koşullar",
      and: "ve",
      PrivacyPolicy: " Gizlilik Politikası",
      IUnderstand: "Anladım",
      PlaceOrder: "Siparişi Ver",

      Categories: "Kategoriler",
      PriceRange: "Fiyat Aralığı",
      ApplyFilter: "Filtreyi Uygula",
      FilterbyBrand: "Markaya Göre Filtrele",
      FilterbyColor: "Renge Göre Filtrele",
      ClearAll: "Tümünü Temizle",
      SearchProducts: "Ürün Ara",
      SortBy: "Sırala",
      View: "Görünüm",
      Electronics: "Elektronik",
      MobilePhonesandAccessories: "Cep Telefonları ve Aksesuarları",
      ComputersandLaptops: "Bilgisayarlar ve Dizüstü Bilgisayarlar",
      HeadphonesandAudioDevices: "Kulaklıklar ve Ses Cihazları",
      SmartDevices: "Akıllı Cihazlar",
      Furniture: "Mobilya",
      Bedrooms: "Yatak Odaları",
      Sofasandseating: "Koltuklar ve Oturma Alanları",
      Kitchensandhouseholdappliances: "Mutfak ve Ev Aletleri",
      Decorandlighting: "Dekorasyon ve Aydınlatma",
      Clothing: "Giyim",
      MensClothing: "Erkek Giyim",
      ChildrensClothing: "Çocuk Giyim",
      Shoes: "Ayakkabılar",
      ClothingAccessories: "Giyim Aksesuarları",
      Jewelry: "Takı",
      MensRings: "Erkek Yüzükleri",
      BraceletsandNecklaces: "Bilezikler ve Kolye",
      Watches: "Saatler",
      MetalAccessories: "Metal Aksesuarlar",
      Needhelp: "Yardıma mı ihtiyacınız var? Bizi arayın: +974 3994 1798",
      free1: "🚚 50$ üzeri siparişlerde ücretsiz kargo",
      free2: "🚚 30$ üzeri siparişlerde ücretsiz kargo",
      free3: "🎁 İlk siparişinizde %20 indirim",
      Home: "Anasayfa",
      About: "Hakkımızda",
      Category: "Kategori",
      ProductDetails: "Ürün Detayları",
      Cart: "Sepet",
      Checkout: "Ödeme",
      Featured: "Öne Çıkanlar",
      NewArrivals: "Yeni Gelenler",
      Sale: "İndirim",
      Categories: "Kategoriler",
      Searchproducts: "Ürün Ara",
      Thecartisempty: "Sepet boş",
      Total: "Toplam",
      ViewCart: "Sepeti Görüntüle",
      ViewCheckout: "Ödemeyi Görüntüle",
      Contact: "İletişim",
      // megamenu - Turkish
      Clothing: "Giyim",
      MensWear: "Erkek Giyim",
      WomensWear: "Kadın Giyim",
      KidsCollection: "Çocuk Koleksiyonu",
      Sportswear: "Spor Giyim",
      Accessories: "Aksesuar",
      Electronics: "Elektronik",
      Smartphones: "Akıllı Telefonlar",
      Laptops: "Dizüstü Bilgisayarlar",
      AudioDevices: "Ses Cihazları",
      SmartHome: "Akıllı Ev",
      HomeLiving: "Ev ve Yaşam",
      Furniture: "Mobilya",
      Decor: "Dekor",
      Kitchen: "Mutfak",
      Bedding: "Yatak Takımı",
      Lighting: "Aydınlatma",
      Beauty: "Güzellik",
      Skincare: "Cilt Bakımı",
      Makeup: "Makyaj",
      Haircare: "Saç Bakımı",
      Fragrances: "Parfümler",
      PersonalCare: "Kişisel Bakım",
      Megamenu2: "Megamenu2",
      Megamenu: "Megamenu2",
      WOMEN: "KADIN",
      MEN: "ERKEK",
      KIDS: "ÇOCUK",
      ShirtsTops: "Gömlek ve Üst Giyim",
      CoatsOuterwear: "Mont ve Dış Giyim",
      Underwear: "İç Giyim",
      Sweatshirts: "Sweatshirt",
      Dresses: "Elbiseler",
      Swimwear: "Plaj Giyimi",
      Viewall: "Hepsini Gör",
      Shoes: "Ayakkabı",
      Boots: "Botlar",
      Sandals: "Sandaletler",
      Heels: "Topuklu Ayakkabılar",
      Loafers: "Loafer Ayakkabılar",
      Slippers: "Terlikler",
      Oxfords: "Oxford Ayakkabılar",
      Handbags: "El Çantaları",
      Eyewear: "Gözlük",
      Hats: "Şapkalar",
      Watches: "Saatler",
      Jewelry: "Takı ve Mücevher",
      Belts: "Kemerler",
      SpecialtySizes: "Özel Bedenler",
      PlusSize: "Büyük Beden",
      Petite: "Minyon Beden",
      WideShoes: "Geniş Kalıp Ayakkabı",
      NarrowShoes: "Dar Kalıp Ayakkabı",
    },
    // {coin === "USD" && "$" }
    // {coin === "QAR" && "﷼" }
    // {coin === "TRY" && "₺" }
  };
  const Currency = {
    USD: {
      // home==================
      price1: 1299,
      price2: 1399,
      mouse: 89,
      mousekeyboard: 149,
      ca: 165,
      item2: 700,
      item3: 1000,
      item4: 100,
      item5: 2000,
      item7: 291,
      New1: 87.5,
      New2: 39.99,
      New3: 45.0,
      shop1: 4.99,
      shop2: 12.99,
    },
    QAR: {
      price1: 4729,
      price2: 5093,
      mouse: 324,
      mousekeyboard: 542,
      ca: 600,
      item2: 2548,
      item3: 3640,
      item4: 364,
      item5: 7280,
      item7: 1060,
      New1: 319,
      New2: 146,
      New3: 164,
      shop1: 18,
      shop2: 47,
    },
    TRY: {
      price1: 55857,
      price2: 60157,
      mouse: 3827,
      mousekeyboard: 6407,
      ca: 7095,
      item2: 30100,
      item3: 43000,
      item4: 4300,
      item5: 86000,
      item7: 12513,
      New1: 3762,
      New2: 1719,
      New3: 1935,
      shop1: 215,
      shop2: 559,
    },
  };
  const [pro, setPro] = useState(() => {
    return localStorage.getItem("pro") || "en";
  });
  useEffect(() => {
    localStorage.setItem("pro", pro);
  }, [pro]);

  const ProDetails = {
    item1: {},
  };
  return (
    <>
      <LangContext.Provider
        value={{ lang, setLang, trasnaltions, coin, setCoin, Currency }}
      >
        <CartProvider>
          <Router>
            <Navbar />
            <Routes>
              <Route path="/" element={<Home />} />
              <Route path="/About" element={<About />} />
              <Route path="/Contact" element={<Contact />} />
              <Route path="/ProductDetails" element={<ProductDetails />} />
              <Route path="/Cart" element={<Cart />} />
              <Route path="/Checkout" element={<Checkout />} />
              <Route path="/Category" element={<Category />} />
            </Routes>
            <Footer />
          </Router>
        </CartProvider>
      </LangContext.Provider>
    </>
  );
}

export default App;
